config/routes.rb
SampleApp::Application.routes.draw do

  resources :host_family_photos

  resources :student_hostfamily_pictures

  get "news_updates/newslist"
  get "news_updates/newsdetails"
  resources :news_updates

  get "newhope_teams/advisor"
  get "newhope_teams/team"
  get "newhope_teams/all"
  
  resources :newhope_teams

  get "services/general"

  get "services/dayschool"

  get "services/boardingschool"

  get "services/publicschool"

  get "services/undergraduate"

  get "services/graduate"

  get "services/hostfamily"

  get "services/hostfamilyapplication"

  get "services/docwriting"

  get "services/followup"
  get "services/news"
  get "services/newsdetails"
  get "services/summercamp"

  resources :highschool_rankings

  get "success_cases/allstudent"
  get "success_cases/highschool"
  get "success_cases/undergraduate"
  get "success_cases/graduate"
  get "success_cases/other"
  
  resources :success_cases

  resources :locations

  resources :graduate_school_rankings

  resources :college_rankings

  resources :college_lists

  resources :high_school_lists

  resources :host_family_infos

  resources :service_requests

  resources :service_grades

  resources :translations

  get "host_families/qualification"
  get "host_families/applicationform"
  get "host_families/whynewhope"
  get "host_families/whatishomestay"
  get "host_families/faq"
  get "host_families/homestayphoto"
  get "host_families/showhomestayphoto"
  get "host_families/servicerequestform"
  get "host_families/availablehomestay"
  get "host_families/responsibility"
  get "host_families/guideline"
  get "host_families/question"
  post "host_families/submitquestion"
  get "host_families/showhostfamilyphoto"
  get "host_families/news"
  get "host_families/newsdetails"

  get "colleges/collegedetail"
  get "colleges/collegelist"
  get "colleges/bachelor"
  get "colleges/msphd"
  get "colleges/communitycollege"
  get "colleges/universityrank"
  get "colleges/collegerank"
  get "colleges/graduateschoolrank"
  get "colleges/news"
  get "colleges/newsdetails"

  get "high_schools/highschooldetail"
  get "high_schools/allhighschool"
  get "high_schools/privateday"
  get "high_schools/privateboarding"
  get "high_schools/public"
  get "high_schools/rank"
  get "high_schools/applicationprocedure"
  get "high_schools/otherservice"
  get "high_schools/academicservice"
  get "high_schools/news"
  get "high_schools/newsdetails"
  
  get "testimonials/parent"
  get "testimonials/student"
  get "testimonials/hostfamily"
  get "testimonials/other"
  get "testimonials/parent1"
  get "testimonials/student1"
  get "testimonials/hostfamily1"
  get "testimonials/other1"
  get "testimonials/detail"
  
  resources :sessions, :only => [:new, :create, :destroy]

  get "users/micropost"
  resources :users do
	member do
		get :following, :followers
	end
  end

  resources :microposts, :only => [:index, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  

  
  
    match '/home', :to => 'pages#home'
	match '/contact', :to => 'pages#contact'
	match '/question', :to => 'pages#question'
	match '/about', :to => 'pages#about'
	match '/help', :to => 'pages#help'
	match '/news', :to => 'pages#news'
	match '/successcase', :to => 'pages#successcase'
	match 'testimonial', :to=> 'testimonials#testimoniallist'
	
	match '/signup', :to => 'users#new'
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	match '/mypost', :to => 'users#micropost'
	
	match '/service', :to => 'pages#service'
	match '/ourteam', :to => 'pages#ourteam'
	match '/whynewhope', :to => 'pages#whynewhope'
	

  root :to => "pages#home"

end

app/models/newhope_team.rb
class NewhopeTeam < ActiveRecord::Base	
	has_attached_file :newhope_team_pic, 
		:styles => { :medium => "320x240>", :thumb => "160x120>", :large => "640x480>" },
		:storage => :s3,
		:s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
		:path => ":attachment/:id/:style.:extension",
		:bucket => 'NewHope-Prod'
		
	def force_utf
		if Rails.env.development? 
			attributes.each {|key, value| value.force_encoding('utf-8') if value.encoding != 'utf-8' if value.kind_of?(String) }
		end
	end
end

app/controllers/newhope_teams_controller.rb
class NewhopeTeamsController < ApplicationController
  before_filter :admin_user, :except => [:advisor, :team, :all]
  before_filter :set_layout, :except => [:advisor, :team, :all]
  before_filter :set_layout1, :only => [:advisor, :team, :all]
  
  # GET /newhope_teams
  # GET /newhope_teams.xml
  def index
    @newhope_teams = NewhopeTeam.find(:all, :order=> 'sort_order, updated_at desc').paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @newhope_teams }
    end
  end

  # GET /newhope_teams/1
  # GET /newhope_teams/1.xml
  def show
    @newhope_team = NewhopeTeam.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @newhope_team }
    end
  end

  # GET /newhope_teams/new
  # GET /newhope_teams/new.xml
  def new
    @newhope_team = NewhopeTeam.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @newhope_team }
    end
  end

  # GET /newhope_teams/1/edit
  def edit
    @newhope_team = NewhopeTeam.find(params[:id])
  end

  # POST /newhope_teams
  # POST /newhope_teams.xml
  def create
    @newhope_team = NewhopeTeam.new(params[:newhope_team])

    respond_to do |format|
      if @newhope_team.save
        format.html { redirect_to(@newhope_team, :notice => 'Newhope team was successfully created.') }
        format.xml  { render :xml => @newhope_team, :status => :created, :location => @newhope_team }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @newhope_team.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /newhope_teams/1
  # PUT /newhope_teams/1.xml
  def update
    @newhope_team = NewhopeTeam.find(params[:id])

    respond_to do |format|
      if @newhope_team.update_attributes(params[:newhope_team])
        format.html { redirect_to(@newhope_team, :notice => 'Newhope team was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @newhope_team.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /newhope_teams/1
  # DELETE /newhope_teams/1.xml
  def destroy
    @newhope_team = NewhopeTeam.find(params[:id])
    @newhope_team.destroy

    respond_to do |format|
      format.html { redirect_to(newhope_teams_url) }
      format.xml  { head :ok }
    end
  end
  
  def all
	@title = "New Hope Team"
	@newhope_teams = NewhopeTeam.find(:all, :conditions=>['status=?', 'Active'], :order=>"sort_order, updated_at desc").paginate(:page => params[:page], :per_page => 2)
	@translation = Translation.find_by_nm('newhopeteam.introduction')
  end
  
  def advisor
	@title = "New Hope Team - Advisor"
	#@newhope_teams = NewhopeTeam.find_all_by_record_type('Advisor').paginate(:page => params[:page], :per_page => 3)
	@newhope_teams = NewhopeTeam.find(:all, :conditions=>['record_type=? and status=?', 'Advisor', 'Active'], :order=>'sort_order, updated_at desc').paginate(:page => params[:page], :per_page => 3)
  end
  
  def team
    branch_name = params[:branch_name]
	if (branch_name.nil?) 
		if I18n.locale != session[:prev_locale]
			branch_name = session[:prec_branch_name]
		else
			redirect_to ourteam_path
		end
	end
	
	
	if (branch_name == "Xian")
		@titlelabel = 'label.ourteam.china.xian'
	elsif (branch_name == "Chicago")
		@titlelabel = 'label.ourteam.usa.chicago'
	else
		@titlelabel = ""
	end
	
	@title = "New Hope Team - #{branch_name}"
	#@newhope_teams = NewhopeTeam.find_all_by_branch_name_en(branch_name).paginate(:page => params[:page], :per_page => 3)
	@newhope_teams = NewhopeTeam.find(:all, :conditions=>['branch_name_en=? and status=?', branch_name, 'Active'], :order=>"sort_order, updated_at desc").paginate(:page => params[:page], :per_page => 3)
	
	session[:prev_locale] = I18n.locale
	session[:prec_branch_name] = branch_name
  end
  
  private
  def set_layout
		@curr_menu = "layouts/user_menu"
		@curr_layout = "layouts/user_layout"
  end
  
  def set_layout1
		@curr_menu = "layouts/ourteam_menu"
		@curr_layout = "layouts/user_layout"
  end
end

app/helpers/newhope_teams_helper.rb
module NewhopeTeamsHelper
end

app/views/newhope_teams/_form.html.erb
<%= form_for @newhope_team, :html => { :multipart => true } do |f| %>
  
  <% @newhope_team.force_utf %>
  <% if @newhope_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newhope_team.errors.count, "error") %> prohibited this newhope_team from being saved:</h2>

      <ul>
      <% @newhope_team.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_en %><br />
    <%= f.text_field :name_en %>
  </div>
  <div class="field">
    <%= f.label :name_cn %><br />
    <%= f.text_field :name_cn %>
  </div>
  <div class="field">
    <%= f.label :title_en %><br />
	<%= f.select(:title_en, 
					[
					    "Employee", "Senior Advisor", "CEO", "CFO", "CIO", "Other"
					]
	) %>
  </div>
  <div class="field">
    <%= f.label :title_cn %><br />
    <%= f.text_field :title_cn %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :record_type %><br />
	<%= f.select(:record_type, 
					[
					    "Employee", "Advisor", "Other"
					]
	) %>
  </div>
  <div class="field">
    <%= f.label :branch_name_en %><br />
	<%= f.select(:branch_name_en, 
					[
					   "", ["Xi'an", "Xian"], "Chicago"
					]
	) %>
  </div>
  <div class="field">
    <%= f.label :branch_name_cn %><br />
    <%= f.text_field :branch_name_cn %>
  </div>
  <div class="field">
    <%= f.label :country_en %><br />
	<%= f.select(:country_en, 
					[
					    "China", "USA", "Other"
					]
	) %>
  </div>
  <div class="field">
    <%= f.label :country_cn %><br />
    <%= f.text_field :country_cn %>
  </div>
  
  <div class="field">
    <%= f.label :newhope_team_pic %>: <%= @newhope_team.newhope_team_pic.url %><br />
    <%= f.file_field :newhope_team_pic %>
  </div>
  
  <div class="field">
    <%= f.label :resume %><br />
    <%= f.text_area :resume, :rows => 20, :cols => 80 %>
  </div>
  <div class="field">
    <%= f.label :sort_order %><br />
    <%= f.text_field :sort_order, :size => 3 %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
	<%= f.select(:status, 
					[
					    "Active", "Inactive"
					]
	) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newhope_teams/advisor.html.erb
<h1><%= t('header.label.ourteam') %> -> <%= t('label.ourteam.advisor') %></h1>

<%= will_paginate @newhope_teams %>

<hr size=10></hr>

<table class="nhtabclass">

<% @newhope_teams.each do |newhope_team| %>
  <% newhope_team.force_utf %>
  <tr>
    <td class="nhtabtdclasstop" width=20%>
		<%= image_tag(newhope_team.newhope_team_pic.url(:large), :height => '200', :width => '160', :alt => "New Hope International Education", :class => "round") %>
	</td>
    <td>
		<b><%= raw(newhope_team.name_cn) %></b><br />
		<%= raw(newhope_team.resume) %>
	</td>
  </tr>
<% end %>

</table>

<%= will_paginate @newhope_teams %>

app/views/newhope_teams/all.html.erb
<h1><%= t('label.ourteam.newhope') %></h1> 
<%= will_paginate @newhope_teams %>

<hr size=10></hr>

<%   @translation.force_utf %>

<p>
	<%= tt(@translation) %>
</p>

<hr size=10></hr>

<table class="nhtabclass">

<% @newhope_teams.each do |newhope_team| %>
  <% newhope_team.force_utf %>
  <tr>
    <td class="nhtabtdclasstop" width=20%>
		<!--
		<%= image_tag("/images/newhopeteam/#{newhope_team.pic}", :height => '200', :width => '160', :alt => "New Hope International Education", :class => "round") %>
		-->
		<%= image_tag(newhope_team.newhope_team_pic.url(:large), :height => '200', :width => '160', :alt => "New Hope International Education", :class => "round") %>
	</td>
    <td>
		<b><%= raw(newhope_team.name_cn) %></b><br />
		<%= raw(newhope_team.resume) %>
	<hr size=10></hr>
	</td>
  </tr>
<% end %>

</table>

<%= will_paginate @newhope_teams %>

app/views/newhope_teams/edit.html.erb
<h1>Editing newhope_team</h1>

<%= render 'form' %>

<%= link_to 'Show', @newhope_team %> |
<%= link_to 'Back', newhope_teams_path %>

app/views/newhope_teams/index.html.erb
<h1>Listing newhope_teams</h1>

<%= will_paginate @newhope_teams %>

<table>
  <tr>
    <th>Name en</th>
    <th>Name cn</th>
    <th>Title en</th>
    <th>Title cn</th>
	<!--
    <th>Email</th>
    <th>Phone</th>
	-->
    <th>Record type</th>
	<!--
    <th>Branch name en</th>
    <th>Branch name cn</th>
    <th>Country en</th>
    <th>Country cn</th>
    <th>Pic</th>
    <th>Resume</th>
    <th>Sort order</th>
    <th>Status</th>
	-->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @newhope_teams.each do |newhope_team| %>
  <% newhope_team.force_utf %>
  <tr>
    <td><%= newhope_team.name_en %></td>
    <td><%= newhope_team.name_cn %></td>
    <td><%= newhope_team.title_en %></td>
    <td><%= newhope_team.title_cn %></td>
	<!--
    <td><%= newhope_team.email %></td>
    <td><%= newhope_team.phone %></td>
	-->
    <td><%= newhope_team.record_type %></td>
	<!--
    <td><%= newhope_team.branch_name_en %></td>
    <td><%= newhope_team.branch_name_cn %></td>
    <td><%= newhope_team.country_en %></td>
    <td><%= newhope_team.country_cn %></td>
    <td><%= newhope_team.pic %></td>
    <td><%= newhope_team.resume %></td>
    <td><%= newhope_team.sort_order %></td>
	-->
    <td><%= newhope_team.status %></td>
    <td><%= link_to 'Show', newhope_team %></td>
    <td><%= link_to 'Edit', edit_newhope_team_path(newhope_team) %></td>
    <td><%= link_to 'Destroy', newhope_team, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @newhope_teams %>

<br />

<%= link_to 'New Newhope team', new_newhope_team_path %>

app/views/newhope_teams/new.html.erb
<h1>New newhope_team</h1>

<%= render 'form' %>

<%= link_to 'Back', newhope_teams_path %>

app/views/newhope_teams/show.html.erb
<% @newhope_team.force_utf %>

<p id="notice"><%= notice %></p>

<p>
  <b>Name en:</b>
  <%= @newhope_team.name_en %>
</p>

<p>
  <b>Name cn:</b>
  <%= @newhope_team.name_cn %>
</p>

<p>
  <b>Title en:</b>
  <%= @newhope_team.title_en %>
</p>

<p>
  <b>Title cn:</b>
  <%= @newhope_team.title_cn %>
</p>

<p>
  <b>Email:</b>
  <%= @newhope_team.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @newhope_team.phone %>
</p>

<p>
  <b>Record type:</b>
  <%= @newhope_team.record_type %>
</p>

<p>
  <b>Branch name en:</b>
  <%= @newhope_team.branch_name_en %>
</p>

<p>
  <b>Branch name cn:</b>
  <%= @newhope_team.branch_name_cn %>
</p>

<p>
  <b>Country en:</b>
  <%= @newhope_team.country_en %>
</p>

<p>
  <b>Country cn:</b>
  <%= @newhope_team.country_cn %>
</p>

<p>
  <b>Pic: <%= @newhope_team.newhope_team_pic.url %></b>
  <%= image_tag(@newhope_team.newhope_team_pic.url(:thumb)) %>
</p>

<p>
  <b>Resume:</b>
  <%= @newhope_team.resume %>
</p>

<p>
  <b>Sort order:</b>
  <%= @newhope_team.sort_order %>
</p>

<p>
  <b>Status:</b>
  <%= @newhope_team.status %>
</p>


<%= link_to 'Edit', edit_newhope_team_path(@newhope_team) %> |
<%= link_to 'Back', newhope_teams_path %>

app/views/newhope_teams/team.html.erb
<h1><%= t('header.label.ourteam') %> -> <%= t("#{@titlelabel}") %></h1>

<hr size=10></hr>

<%= will_paginate @newhope_teams %>

<table class="nhtabclass">

<% @newhope_teams.each do |newhope_team| %>
  <% newhope_team.force_utf %>
  <% theemail = "<A href='mailto:" + newhope_team.email + "'>" + newhope_team.email + "</a>" %>
  <tr>
    <td class="nhtabtdclasstop" width=20%>
		<!--
		<%= image_tag("/images/newhopeteam/#{newhope_team.pic}", :height => '200', :width => '160', :alt => "New Hope International Education", :class => "round") %>
		-->
		<%= image_tag(newhope_team.newhope_team_pic.url(:large), :height => '200', :width => '160', :alt => "New Hope International Education", :class => "round") %>
	</td>
    <td>
		<b><%= raw(newhope_team.name_cn) %></b><br />
		<%= raw(newhope_team.resume) %>
		<br><br>
		<font size=1><%= t('label.ourteam.phone') %>:</font>&nbsp;<%= raw(newhope_team.phone) %>&nbsp;&nbsp;&nbsp;<font size=1>
		<%= t('label.ourteam.email') %>:</font>&nbsp;<%= raw(theemail) %>
		<hr size=10></hr>
	</td>
  </tr>
<% end %>
</table>


<%= will_paginate @newhope_teams %>