config/routes.rb
SampleApp::Application.routes.draw do

  resources :host_family_photos

  resources :student_hostfamily_pictures

  get "news_updates/newslist"
  get "news_updates/newsdetails"
  resources :news_updates

  get "newhope_teams/advisor"
  get "newhope_teams/team"
  get "newhope_teams/all"
  
  resources :newhope_teams

  get "services/general"

  get "services/dayschool"

  get "services/boardingschool"

  get "services/publicschool"

  get "services/undergraduate"

  get "services/graduate"

  get "services/hostfamily"

  get "services/hostfamilyapplication"

  get "services/docwriting"

  get "services/followup"
  get "services/news"
  get "services/newsdetails"
  get "services/summercamp"

  resources :highschool_rankings

  get "success_cases/allstudent"
  get "success_cases/highschool"
  get "success_cases/undergraduate"
  get "success_cases/graduate"
  get "success_cases/other"
  
  resources :success_cases

  resources :locations

  resources :graduate_school_rankings

  resources :college_rankings

  resources :college_lists

  resources :high_school_lists

  resources :host_family_infos

  resources :service_requests

  resources :service_grades

  resources :translations

  get "host_families/qualification"
  get "host_families/applicationform"
  get "host_families/whynewhope"
  get "host_families/whatishomestay"
  get "host_families/faq"
  get "host_families/homestayphoto"
  get "host_families/showhomestayphoto"
  get "host_families/servicerequestform"
  get "host_families/availablehomestay"
  get "host_families/responsibility"
  get "host_families/guideline"
  get "host_families/question"
  post "host_families/submitquestion"
  get "host_families/showhostfamilyphoto"
  get "host_families/news"
  get "host_families/newsdetails"

  get "colleges/collegedetail"
  get "colleges/collegelist"
  get "colleges/bachelor"
  get "colleges/msphd"
  get "colleges/communitycollege"
  get "colleges/universityrank"
  get "colleges/collegerank"
  get "colleges/graduateschoolrank"
  get "colleges/news"
  get "colleges/newsdetails"

  get "high_schools/highschooldetail"
  get "high_schools/allhighschool"
  get "high_schools/privateday"
  get "high_schools/privateboarding"
  get "high_schools/public"
  get "high_schools/rank"
  get "high_schools/applicationprocedure"
  get "high_schools/otherservice"
  get "high_schools/academicservice"
  get "high_schools/news"
  get "high_schools/newsdetails"
  
  get "testimonials/parent"
  get "testimonials/student"
  get "testimonials/hostfamily"
  get "testimonials/other"
  get "testimonials/parent1"
  get "testimonials/student1"
  get "testimonials/hostfamily1"
  get "testimonials/other1"
  get "testimonials/detail"
  
  resources :sessions, :only => [:new, :create, :destroy]

  get "users/micropost"
  resources :users do
	member do
		get :following, :followers
	end
  end

  resources :microposts, :only => [:index, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  

  
  
    match '/home', :to => 'pages#home'
	match '/contact', :to => 'pages#contact'
	match '/question', :to => 'pages#question'
	match '/about', :to => 'pages#about'
	match '/help', :to => 'pages#help'
	match '/news', :to => 'pages#news'
	match '/successcase', :to => 'pages#successcase'
	match 'testimonial', :to=> 'testimonials#testimoniallist'
	
	match '/signup', :to => 'users#new'
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	match '/mypost', :to => 'users#micropost'
	
	match '/service', :to => 'pages#service'
	match '/ourteam', :to => 'pages#ourteam'
	match '/whynewhope', :to => 'pages#whynewhope'
	

  root :to => "pages#home"

end

app/models/translation.rb
# == Schema Information
# Schema version: 20110309201705
#
# Table name: translations
#
#  id            :integer(4)      not null, primary key
#  nm            :string(255)
#  controller_nm :string(255)
#  model_nm      :string(255)
#  action_nm     :string(255)
#  func          :string(255)
#  zw_txt        :text
#  zw2_txt       :text
#  en_txt        :text
#  created_at    :datetime
#  updated_at    :datetime
#

class Translation < ActiveRecord::Base
	validates :nm, :presence => true, :uniqueness => true
	
	def force_utf
		if Rails.env.development? 
			attributes.each {|key, value| value.force_encoding('utf-8') if value.encoding != 'utf-8' if value.kind_of?(String) }
		end
	end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_filter :admin_user
  before_filter :set_layout
  
  # GET /translations
  # GET /translations.xml
  def index
    @translations = Translation.all.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @translations }
    end
  end

  # GET /translations/1
  # GET /translations/1.xml
  def show
    @translation = Translation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @translation }
    end
  end

  # GET /translations/new
  # GET /translations/new.xml
  def new
    @translation = Translation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @translation }
    end
  end

  # GET /translations/1/edit
  def edit
    @translation = Translation.find(params[:id])
  end

  # POST /translations
  # POST /translations.xml
  def create
    @translation = Translation.new(params[:translation])

    respond_to do |format|
      if @translation.save
        format.html { redirect_to(@translation, :notice => 'Translation was successfully created.') }
        format.xml  { render :xml => @translation, :status => :created, :location => @translation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @translation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /translations/1
  # PUT /translations/1.xml
  def update
    @translation = Translation.find(params[:id])

    respond_to do |format|
      if @translation.update_attributes(params[:translation])
        format.html { redirect_to(@translation, :notice => 'Translation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @translation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.xml
  def destroy
    @translation = Translation.find(params[:id])
    @translation.destroy

    respond_to do |format|
      format.html { redirect_to(translations_url) }
      format.xml  { head :ok }
    end
  end
  
  private
	
	def set_layout
		@curr_menu = "layouts/user_menu"
		@curr_layout = "layouts/user_layout"
	end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/_form.html.erb
<%   @translation.force_utf %>

<%= form_for(@translation) do |f| %>
  <% if @translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translation.errors.count, "error") %> prohibited this translation from being saved:</h2>

      <ul>
      <% @translation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nm %><br />
    <%= f.text_field :nm %>
  </div>
  <div class="field">
    <%= f.label :controller_nm %><br />
    <%= f.text_field :controller_nm %>
  </div>
  <div class="field">
    <%= f.label :model_nm %><br />
    <%= f.text_field :model_nm %>
  </div>
  <div class="field">
    <%= f.label :action_nm %><br />
    <%= f.text_field :action_nm %>
  </div>
  <div class="field">
    <%= f.label :func %><br />
    <%= f.text_field :func %>
  </div>
  <div class="field">
    <%= f.label :en_txt %><br />
    <%= f.text_area :en_txt, :rows=>30, :cols=>80 %>
  </div>
  <div class="field">
    <%= f.label :cn_txt %><br />
    <%= f.text_area :zw_txt, :rows=>30, :cols=>80 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/translations/edit.html.erb
<h1>Editing translation</h1>

<%= render 'form' %>

<%= link_to 'Show', @translation %> |
<%= link_to 'Back', translations_path %>

app/views/translations/index.html.erb
<h1>Listing translations</h1>

<%= will_paginate @translations %>

<table>
  <tr>
    <th>Nm</th>
	<!--
    <th>Controller nm</th>
    <th>Model nm</th>
    <th>Action nm</th>
    <th>Func</th>
	-->
    <th>Cn txt</th>
	<!--
    <th>En txt</th>
	-->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @translations.each do |translation| %>
	<%   translation.force_utf %>
  <tr>
    <td><%= translation.nm %></td>
	<!--
    <td><%= translation.controller_nm %></td>
    <td><%= translation.model_nm %></td>
    <td><%= translation.action_nm %></td>
    <td><%= translation.func %></td>
	-->
    <td><%= truncate(translation.zw_txt) %></td>
	<!--
    <td><%= truncate(translation.en_txt) %></td>
	-->
    <td><%= link_to 'Show', translation %></td>
    <td><%= link_to 'Edit', edit_translation_path(translation) %></td>
    <td><%= link_to 'Destroy', translation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @translations %>

<br />

<%= link_to 'New Translation', new_translation_path %>

app/views/translations/new.html.erb
<h1>New translation</h1>

<%= render 'form' %>

<%= link_to 'Back', translations_path %>

app/views/translations/show.html.erb
<% @translation.force_utf %>

<p id="notice"><%= notice %></p>

<p>
  <b>Nm:</b>
  <%= @translation.nm %>
</p>

<p>
  <b>Controller nm:</b>
  <%= @translation.controller_nm %>
</p>

<p>
  <b>Model nm:</b>
  <%= @translation.model_nm %>
</p>

<p>
  <b>Action nm:</b>
  <%= @translation.action_nm %>
</p>

<p>
  <b>Func:</b>
  <%= @translation.func %>
</p>

<p>
  <b>En txt:</b><br>
  <%= raw(@translation.en_txt) %>
</p>

<p>
  <b>Cn txt:</b><br>
  <%= raw(@translation.zw_txt) %>
</p>


<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>