config/routes.rb
SampleApp::Application.routes.draw do

  resources :host_family_photos

  resources :student_hostfamily_pictures

  get "news_updates/newslist"
  get "news_updates/newsdetails"
  resources :news_updates

  get "newhope_teams/advisor"
  get "newhope_teams/team"
  get "newhope_teams/all"
  
  resources :newhope_teams

  get "services/general"

  get "services/dayschool"

  get "services/boardingschool"

  get "services/publicschool"

  get "services/undergraduate"

  get "services/graduate"

  get "services/hostfamily"

  get "services/hostfamilyapplication"

  get "services/docwriting"

  get "services/followup"
  get "services/news"
  get "services/newsdetails"
  get "services/summercamp"

  resources :highschool_rankings

  get "success_cases/allstudent"
  get "success_cases/highschool"
  get "success_cases/undergraduate"
  get "success_cases/graduate"
  get "success_cases/other"
  
  resources :success_cases

  resources :locations

  resources :graduate_school_rankings

  resources :college_rankings

  resources :college_lists

  resources :high_school_lists

  resources :host_family_infos

  resources :service_requests

  resources :service_grades

  resources :translations

  get "host_families/qualification"
  get "host_families/applicationform"
  get "host_families/whynewhope"
  get "host_families/whatishomestay"
  get "host_families/faq"
  get "host_families/homestayphoto"
  get "host_families/showhomestayphoto"
  get "host_families/servicerequestform"
  get "host_families/availablehomestay"
  get "host_families/responsibility"
  get "host_families/guideline"
  get "host_families/question"
  post "host_families/submitquestion"
  get "host_families/showhostfamilyphoto"
  get "host_families/news"
  get "host_families/newsdetails"

  get "colleges/collegedetail"
  get "colleges/collegelist"
  get "colleges/bachelor"
  get "colleges/msphd"
  get "colleges/communitycollege"
  get "colleges/universityrank"
  get "colleges/collegerank"
  get "colleges/graduateschoolrank"
  get "colleges/news"
  get "colleges/newsdetails"

  get "high_schools/highschooldetail"
  get "high_schools/allhighschool"
  get "high_schools/privateday"
  get "high_schools/privateboarding"
  get "high_schools/public"
  get "high_schools/rank"
  get "high_schools/applicationprocedure"
  get "high_schools/otherservice"
  get "high_schools/academicservice"
  get "high_schools/news"
  get "high_schools/newsdetails"
  
  get "testimonials/parent"
  get "testimonials/student"
  get "testimonials/hostfamily"
  get "testimonials/other"
  get "testimonials/parent1"
  get "testimonials/student1"
  get "testimonials/hostfamily1"
  get "testimonials/other1"
  get "testimonials/detail"
  
  resources :sessions, :only => [:new, :create, :destroy]

  get "users/micropost"
  resources :users do
	member do
		get :following, :followers
	end
  end

  resources :microposts, :only => [:index, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  

  
  
    match '/home', :to => 'pages#home'
	match '/contact', :to => 'pages#contact'
	match '/question', :to => 'pages#question'
	match '/about', :to => 'pages#about'
	match '/help', :to => 'pages#help'
	match '/news', :to => 'pages#news'
	match '/successcase', :to => 'pages#successcase'
	match 'testimonial', :to=> 'testimonials#testimoniallist'
	
	match '/signup', :to => 'users#new'
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	match '/mypost', :to => 'users#micropost'
	
	match '/service', :to => 'pages#service'
	match '/ourteam', :to => 'pages#ourteam'
	match '/whynewhope', :to => 'pages#whynewhope'
	

  root :to => "pages#home"

end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_filter :set_layout
  
  def bachelor
	@curr_menu = "layouts/college_menu"
	@title = "US Bechelor School"
	@titlelabel = 'label.college.allcollegelistbs'
	
	@college_lists = CollegeList.find_by_sql("select * from college_lists where highest_degree = 'bs' and status = 'Active'").paginate(:page => params[:page], :per_page => 10) 
	render :action => "collegelist"
  end

  def msphd
	@curr_menu = "layouts/college_menu"
	@title = "US Master & PhD School"
	
	@titlelabel = 'label.college.allcollegelistmsphd'
	@college_lists = CollegeList.find_by_sql("select * from college_lists where highest_degree in ('ms', 'phd') and status = 'Active'").paginate(:page => params[:page], :per_page => 10)
	render :action => "collegelist"
  end

  def communitycollege
	@curr_menu = "layouts/college_menu"
	@title = "US Community College"
	
	@titlelabel = 'label.college.allcollegelistcc'
	@college_lists = CollegeList.find_by_sql("select * from college_lists where highest_degree ='as' and status = 'Active'").paginate(:page => params[:page], :per_page => 10)
	render :action => "collegelist"
  end
  
  def universityrank
	@curr_menu = "layouts/college_menu"
	@title = "US National University Ranking"
	@titlelabel = 'label.college.label.universityrank'
	
	@college_rankings = CollegeRanking.find_by_sql("select * from college_rankings where school_type='university' order by rank")
  end
  
  def collegerank
	@curr_menu = "layouts/college_menu"
	@title = "US Liberal Arts College Ranking"
	@titlelabel = 'label.college.label.collegerank'
	
	@college_rankings = CollegeRanking.find_by_sql("select * from college_rankings where school_type='college' order by rank")
	render :action=> "universityrank"
  end
  
  def graduateschoolrank
	@curr_menu = "layouts/college_menu"
	@title = "US Graduate School Ranking"
	
	category = params[:category]
	if category.nil?
		if I18n.locale != session[:prev_locale]
			category = session[:pre_category]
		else
			redirect_to colleges_universityrank_path
		end
	end
	
	if category == 'business'
		@titlelabel = 'label.college.label.gsbusinessrank'
	elsif category == 'education'
		@titlelabel = 'label.college.label.gseducationrank'
	elsif category == 'engineering'
		@titlelabel = 'label.college.label.gsengineeringrank'
	elsif category == 'law'
		@titlelabel = 'label.college.label.gslawrank'
	elsif category == 'medical'
		@titlelabel = 'label.college.label.gsmedicalrank'
	elsif category == 'science'
		@titlelabel = 'label.college.label.gssciencerank'
	elsif category == 'library'
		@titlelabel = 'label.college.label.gslibraryrank'
	elsif category == 'social'
		@titlelabel = 'label.college.label.gssocialrank'
	elsif category == 'health'
		@titlelabel = 'label.college.label.gshealthrank'
	elsif category == 'public'
		@titlelabel = 'label.college.label.gspublicrank'
	elsif category == 'fine'
		@titlelabel = 'label.college.label.gsfinerank'
	end
	
	@graduate_school_rankings = GraduateSchoolRanking.find_all_by_category(category)
	
	session[:prev_locale] = I18n.locale
	session[:pre_category] = category
  end
  
  def collegelist
	@title = "US College List"
	@titlelabel = 'label.college.allcollegelist'
	
	@college_lists = CollegeList.find(:all, :conditions => ["status = 'Active'"], :order => "updated_at desc").paginate(:page => params[:page], :per_page => 10)
  end
  
  def collegedetail
	@title = "College Details"
	college_id = params[:id]
	if college_id.nil?
		if I18n.locale != session[:prev_locale]
			college_id = session[:prec_college_id]
		else
			redirect_to colleges_collegelist_path
		end
	end
	
	@college_list = CollegeList.find_by_id(college_id)
	
	#@pics = @college_list.pics.split

	session[:prev_locale] = I18n.locale
	session[:prec_college_id] = college_id
  end
  
  def news
	@title = "Latest College News"
	
    news_type = params[:news_type]
	if (news_type.nil? || news_type.empty?) 
		news_type = "CollegeNews"
	end
	
	set_label(news_type)
	if (news_type.nil? || news_type.empty?)
		@news_updates = NewsUpdate.all.paginate(:page => params[:page], :per_page => 10)
	else
		@news_updates = NewsUpdate.find_all_by_news_type(news_type).paginate(:page => params[:page], :per_page => 10)
	end
  end
  
  def newsdetails
	@title = "College News Details"
	set_label(params[:news_type])
	
	news_id = params[:id]
	if news_id.nil?
		if I18n.locale != session[:prev_locale]
			news_id = session[:prec_news_id]
		else
			redirect_to high_school_news_path
		end
	end
	
	@news_update = NewsUpdate.find(news_id)

	session[:prev_locale] = I18n.locale
	session[:prec_news_id] = news_id
  end

  private
	def set_layout
		@curr_layout = "layouts/user_layout"
		@curr_menu = "layouts/college_menu"
	end
	
	def set_label(news_type)
		if news_type == "CollegeNews"
			@titlelabel = "label.highschool.label.latestnews"
		elsif news_type == "CollegeGraduate"
			@titlelabel = "label.highschool.label.hsgraduate"
		elsif news_type == "CollegeFAQ"
			@titlelabel = "label.hostfamily.homestay.faq"
		else
			@titlelabel = "header.label.latestnews"
		end
	end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/bachelor.html.erb
<h1>Colleges#bachelor</h1>
<p>Find me in app/views/colleges/bachelor.html.erb</p>

app/views/colleges/collegedetail.html.erb
<h1><%= t('label.college.college') %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font size=2><%= link_to back_button %></font> </h1>

<hr size=10></hr>

<%   @college_list.force_utf %>
<p id="notice"><%= notice %></p>

<fieldset>
	<legend>
		<%= link_to "#{@college_list.name_en} #{@college_list.name_cn}",  "http://#{@college_list.website}", :target=> :blank %>
	</legend>
	
	<% if @college_list.college_pdf.url == "/college_pdfs/original/missing.png" %>
	<table class="nhtabclass">
	

		<tr>
			<td colspan=3 class="nhtabtdclasstop"><%= image_tag(@college_list.college_pic_1.url(:large), :height => '250', :width => '330', :alt => "New Hope International Education", :class => "round") %></td>
			<td colspan=3 class="nhtabtdclasstop"><%= image_tag(@college_list.college_pic_2.url(:large), :height => '250', :width => '330', :alt => "New Hope International Education", :class => "round") %></td>
		</tr>

		
		<tr>
			<td colspan=6 class="nhtabtdclasstop"><%= raw(truncate(@college_list.about_school, :length=> 1000)) %></td>
		</tr>
		
		<tr>
			<td colspan=6><br><h1><%= t('label.college.label.schoolfact') %></h1></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.address') %></td>
			<td colspan=5>
				<%= @college_list.address %>
			</td>
		</tr>
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.url') %></td>
			<td colspan=5>
								<%= link_to @college_list.website,  "http://#{@college_list.website}", :target=> :blank %>
			</td>
			</tr>
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.founded') %></td>
			<td><%= @college_list.founded %></td>
			<td class="nhtabtdclassright"><%= t('label.college.label.schooltype') %></td>
			<td><%= @college_list.school_type %></td>
			
			<td class="nhtabtdclassright"><%= t('label.college.label.totalstudent') %></td>
			<td><%= @college_list.total_student %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.enrollment') %></td>
			<td><%= @college_list.enrollment %></td>
			<td class="nhtabtdclassright"><%= t('label.college.label.acceptancerate') %></td>
			<td><%= @college_list.acceptance_rate %></td>
			
			<td class="nhtabtdclassright"><%= t('label.college.label.teacherstudentratio') %></td>
			<td><%= @college_list.teacher_student_ratio %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.academiccalendar') %></td>
			<td colspan=5><%= @college_list.academic_calendar %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.setting') %></td>
			<td><%= @college_list.setting %></td>
			
			<td class="nhtabtdclassright"><%= t('label.college.label.satscore') %></td>
			<td><%= @college_list.sat_score %></td>
			
			<td></td>
			<td></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.degree') %></td>
			<td colspan=5><%= raw(@college_list.degree) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.ranking') %></td>
			<td colspan=5><%= raw(@college_list.ranking) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.studentinfo') %></td>
			<td colspan=5><%= raw(@college_list.student_info) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.facultyinfo') %></td>
			<td colspan=5><%= raw(@college_list.faculty_info) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.tuitionfee') %></td>
			<td colspan=5><%= raw(@college_list.tuition_fee) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.financialaid') %></td>
			<td colspan=5><%= raw(@college_list.financial_aid) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.popularmajor') %></td>
			<td colspan=5><%= raw(@college_list.popular_major) %></td>
		</tr>
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.specialfeature') %></td>
			<td colspan=5><%= raw(@college_list.special_feature) %></td>
		</tr>
		
		<% if admin_user? %>
			<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.contactinfo') %></td>
			<td colspan=5>
				<%= raw(@college_list.contact_info) %>
			</td>
			</tr>
		<% end %>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.applicationdeadline') %></td>
			<td colspan=5><%= raw(@college_list.application_deadline) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.applicationfee') %></td>
			<td><%= raw(@college_list.application_fee) %></td>
			<td class="nhtabtdclassright"><%= t('label.college.label.applicationmethod') %></td>
			<td><%= raw(@college_list.application_method) %></td>
			<td class="nhtabtdclassright"><%= t('label.college.label.applicationform') %></td>
			<td><%= raw(@college_list.application_form) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.admissionrequirement') %></td>
			<td colspan=5><%= raw(@college_list.admission_requirement) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.applicationmaterial') %></td>
			<td colspan=5><%= raw(@college_list.application_material) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.applicationmustknow') %></td>
			<td colspan=5><%= raw(@college_list.application_mustknow) %></td>
		</tr>
	
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.doubleadmission') %></td>
			<td><%= raw(@college_list.double_admission) %></td>
			<td class="nhtabtdclassright"><%= t('label.college.label.recommendationform') %></td>
			<td><%= raw(@college_list.recommendation_form) %></td>
			<td class="nhtabtdclassright"><%= t('label.college.label.financialform') %></td>
			<td><%= raw(@college_list.financial_form) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.langrequirement') %></td>
			<td colspan=5><%= raw(@college_list.lang_requirement) %></td>
		</tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.dlangrequirement') %></td>
			<td colspan=5><%= raw(@college_list.d_lang_requirement) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.mailtestscore') %></td>
			<td><%= raw(@college_list.mail_test_score) %></td>
			<td class="nhtabtdclassright"><%= t('label.college.label.airporthelp') %></td>
			<td><%= raw(@college_list.airport_help) %></td>
			<td class="nhtabtdclassright"><%= t('label.college.label.boarding') %></td>
			<td><%= raw(@college_list.boarding) %></td>
		</tr>
		
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.notice') %></td>
			<td colspan=5><%= raw(@college_list.notice) %></td>
		</tr>
		
		<!--
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.remark') %></td>
			<td colspan=5><%= raw(@college_list.remark) %></td>
		</tr>
		-->
		
		<!--
		<tr>
			<td class="nhtabtdclassright"><%= t('label.college.label.status') %></td>
			<td colspan=5><%= raw(@college_list.status) %></td>
		</tr>
		-->
		
	</table>
	<% else %>
		<iframe src="http://docs.google.com/gview?url=<%= @college_list.college_pdf.url %>&embedded=true" style="width:700px; height:1000px;" frameborder="0"></iframe>
	<% end %>
</fieldset>

<nav class="text">
	<%= link_to back_button %>
</nav>

app/views/colleges/collegelist.html.erb
<h1><%= t("#{@titlelabel}") %></h1>
<hr size=10></hr>

<%= will_paginate @college_lists %>

<table>
  <tr>
    <th><%= t('label.college.label.name') %></th>
    <th></th>
	<th><%= t('label.college.label.schooltype') %></th>
    <th><%= t('label.college.label.founded') %></th>
    <th><%= t('label.college.label.address') %></th>
    <th><%= t('label.college.label.url') %></th>
	<!--
    <th>Total student</th>
    <th>Enrollment</th>
    <th>Acceptance rate</th>
    <th>Teacher student ratio</th>
    <th>Student info</th>
	<th>Faculty info</th>
    <th>Sat score</th>
    <th>Ranking</th>
    <th>Tuition fee</th>
    <th>Financial aid</th>
    <th>About school</th>
    <th>Academic calendar</th>
    <th>Popular major</th>
    <th>Special feature</th>
    <th>Degree</th>
    <th>Contact info</th>
    <th>Setting</th>
    <th>Pics</th>
    <th>Application deadline</th>
    <th>Applciation fee</th>
    <th>Application method</th>
    <th>Application form</th>
    <th>Application material</th>
    <th>Application mustknow</th>
    <th>Double admission</th>
    <th>Lang requirement</th>
    <th>D lang requirement</th>
    <th>Recommendation form</th>
    <th>Financial form</th>
    <th>Admission requirement</th>
    <th>Mail test score</th>
    <th>Airport help</th>
    <th>Boardidng</th>
    <th>Notice</th>
    <th>Remark</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
	-->
  </tr>

<% @college_lists.each do |college_list| %>
<% college_list.force_utf %>
  <tr>
    <td><%= link_to "#{college_list.name_en}", colleges_collegedetail_path(:id=>college_list) %></td>
    <td><%= college_list.name_cn %></td>
	<td><%= college_list.school_type %></td>
    <td><%= college_list.founded %></td>
    <td><%= college_list.address %></td>
    <td><%= link_to college_list.website,  "http://#{college_list.website}", :target=> :blank %></td>
    
	<!--
    <td><%= college_list.total_student %></td>
    <td><%= college_list.enrollment %></td>
    <td><%= college_list.acceptance_rate %></td>
    <td><%= college_list.teacher_student_ratio %></td>
    <td><%= college_list.student_info %></td>
	<td><%= college_list.faculty_info %></td>
    <td><%= college_list.sat_score %></td>
    <td><%= college_list.ranking %></td>
    <td><%= college_list.tuition_fee %></td>
    <td><%= college_list.financial_aid %></td>
    <td><%= college_list.about_school %></td>
    <td><%= college_list.academic_calendar %></td>
    <td><%= college_list.popular_major %></td>
    <td><%= college_list.special_feature %></td>
    <td><%= college_list.degree %></td>
    <td><%= college_list.contact_info %></td>
    <td><%= college_list.setting %></td>
    <td><%= college_list.pics %></td>
    <td><%= college_list.application_deadline %></td>
    <td><%= college_list.application_fee %></td>
    <td><%= college_list.application_method %></td>
    <td><%= college_list.application_form %></td>
    <td><%= college_list.application_material %></td>
    <td><%= college_list.application_mustknow %></td>
    <td><%= college_list.double_admission %></td>
    <td><%= college_list.lang_requirement %></td>
    <td><%= college_list.d_lang_requirement %></td>
    <td><%= college_list.recommendation_form %></td>
    <td><%= college_list.financial_form %></td>
    <td><%= college_list.admission_requirement %></td>
    <td><%= college_list.mail_test_score %></td>
    <td><%= college_list.airport_help %></td>
    <td><%= college_list.boarding %></td>
    <td><%= college_list.notice %></td>
    <td><%= college_list.remark %></td>
    <td><%= college_list.status %></td>
    <td><%= link_to 'Show', college_list %></td>
    <td><%= link_to 'Edit', edit_college_list_path(college_list) %></td>
    <td><%= link_to 'Destroy', college_list, :confirm => 'Are you sure?', :method => :delete %></td>
	-->
  </tr>
<% end %>
</table>

<%= will_paginate @college_lists %>

app/views/colleges/graduateschoolrank.html.erb
<h1><%= t("#{@titlelabel}") %></h1>
<hr size=10></hr>

<table>
  <tr>
    <th><%= t('label.college.label.rank') %></th>
    <th><%= t('label.college.label.name') %></th>
    <th></th>
    <th><%= t('label.college.label.tuition') %></th>
    <th><%= t('label.college.label.enrollment') %></th>
	<!--
	<th>GPA</th>
	<th>GMAT</th>
    <th>Acceptance rate</th>
    <th>Graduation rate</th>
    <th>Avg Salary/Bonus</th>
	-->
  </tr>

<% @graduate_school_rankings.each do |graduate_school_ranking| %>
<% graduate_school_ranking.force_utf %>
  <tr>
    <td><%= graduate_school_ranking.rank %></td>
	<% if graduate_school_ranking.college_list_id.nil? %>
		<td><%= graduate_school_ranking.name_en %></td>
	<% else %>
		<td><%= link_to "#{graduate_school_ranking.name_en}", colleges_collegedetail_path(:id=>graduate_school_ranking.college_list_id) %></td>
	<% end %>
    <td><%= graduate_school_ranking.name_cn %></td>
    <td><%= graduate_school_ranking.tuition %></td>
    <td><%= graduate_school_ranking.enrollment %></td>
	<!--
    <td><%= graduate_school_ranking.gpa %></td>
	<td><%= graduate_school_ranking.gmat %></td>
    <td><%= graduate_school_ranking.graduation_rate %></td>
    <td><%= graduate_school_ranking.graduation_rate %></td>
    <td><%= graduate_school_ranking.salary %></td>
	-->
  </tr>
<% end %>
</table>

app/views/colleges/msphd.html.erb
<h1>Colleges#msphd</h1>
<p>Find me in app/views/colleges/msphd.html.erb</p>

app/views/colleges/news.html.erb
<h1><%= t("label.college.college") %> -> <%= t("#{@titlelabel}") %></h1>

<hr size=10></hr>

<%= will_paginate @news_updates %>

<table>

<% i = 0 %>
<% @news_updates.each do |news_update| %>
  <% news_update.force_utf %>
  <% i = i + 1 %>
  <tr>
    <td width=1%><%= i %></td>
    <td><%= link_to news_update.title_cn, colleges_newsdetails_path(:id => news_update, :news_type => news_update.news_type) %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @news_updates %>

app/views/colleges/newsdetails.html.erb
<% @news_update.force_utf %>
 
<h1><%= t("label.college.college") %> -> <%= t("#{@titlelabel}") %></h1>

<hr size=10></hr>

<%= link_to back_button %>

<p id="notice"><%= notice %></p>

<p>
  <b><%= @news_update.title_cn %></b>
</p>


<p>
  <%= raw(@news_update.context) %>
</p>

<%= link_to back_button %>

app/views/colleges/undergraduaterank.html.erb
<h1>Undergraduate#rank</h1>
<p>Find me in app/views/colleges/undergraduaterank.html.erb</p>

app/views/colleges/universityrank.html.erb
<h1><%= t("#{@titlelabel}") %></h1>
<hr size=10></hr>

<table>
  <tr>
    <th><%= t('label.college.label.rank') %></th>
    <th><%= t('label.college.label.name') %></th>
    <th></th>
    <th><%= t('label.college.label.tuition') %></th>
    <th><%= t('label.college.label.enrollment') %></th>
    <th><%= t('label.college.label.acceptancerate') %></th>
    <th><%= t('label.college.label.retentionrate') %></th>
    <th><%= t('label.college.label.graduationrate') %></th>
    <th><%= t('label.college.label.classsize') %></th>
    <th><%= t('label.college.label.satact') %></th>
  </tr>

<% @college_rankings.each do |college_ranking| %>
<% college_ranking.force_utf %>
  <tr>
    <td><%= college_ranking.rank %></td>
	<% if college_ranking.college_list_id.nil? %>
		<td><%= college_ranking.name_en %></td>
	<% else %>
		<td><%= link_to "#{college_ranking.name_en}", colleges_collegedetail_path(:id=>college_ranking.college_list_id) %></td>
	<% end %>
    <td><%= college_ranking.name_cn %></td>
    <td><%= college_ranking.tuition %></td>
    <td><%= college_ranking.enrollment %></td>
    <td><%= college_ranking.acceptance_rate %></td>
    <td><%= college_ranking.retention_rate %></td>
    <td><%= college_ranking.graduation_rate %></td>
    <td><%= college_ranking.class_size %></td>
    <td><%= college_ranking.sat_act %></td>
  </tr>
<% end %>
</table>