config/routes.rb
SampleApp::Application.routes.draw do

  resources :host_family_photos

  resources :student_hostfamily_pictures

  get "news_updates/newslist"
  get "news_updates/newsdetails"
  resources :news_updates

  get "newhope_teams/advisor"
  get "newhope_teams/team"
  get "newhope_teams/all"
  
  resources :newhope_teams

  get "services/general"

  get "services/dayschool"

  get "services/boardingschool"

  get "services/publicschool"

  get "services/undergraduate"

  get "services/graduate"

  get "services/hostfamily"

  get "services/hostfamilyapplication"

  get "services/docwriting"

  get "services/followup"
  get "services/news"
  get "services/newsdetails"
  get "services/summercamp"

  resources :highschool_rankings

  get "success_cases/allstudent"
  get "success_cases/highschool"
  get "success_cases/undergraduate"
  get "success_cases/graduate"
  get "success_cases/other"
  
  resources :success_cases

  resources :locations

  resources :graduate_school_rankings

  resources :college_rankings

  resources :college_lists

  resources :high_school_lists

  resources :host_family_infos

  resources :service_requests

  resources :service_grades

  resources :translations

  get "host_families/qualification"
  get "host_families/applicationform"
  get "host_families/whynewhope"
  get "host_families/whatishomestay"
  get "host_families/faq"
  get "host_families/homestayphoto"
  get "host_families/showhomestayphoto"
  get "host_families/servicerequestform"
  get "host_families/availablehomestay"
  get "host_families/responsibility"
  get "host_families/guideline"
  get "host_families/question"
  post "host_families/submitquestion"
  get "host_families/showhostfamilyphoto"
  get "host_families/news"
  get "host_families/newsdetails"

  get "colleges/collegedetail"
  get "colleges/collegelist"
  get "colleges/bachelor"
  get "colleges/msphd"
  get "colleges/communitycollege"
  get "colleges/universityrank"
  get "colleges/collegerank"
  get "colleges/graduateschoolrank"
  get "colleges/news"
  get "colleges/newsdetails"

  get "high_schools/highschooldetail"
  get "high_schools/allhighschool"
  get "high_schools/privateday"
  get "high_schools/privateboarding"
  get "high_schools/public"
  get "high_schools/rank"
  get "high_schools/applicationprocedure"
  get "high_schools/otherservice"
  get "high_schools/academicservice"
  get "high_schools/news"
  get "high_schools/newsdetails"
  
  get "testimonials/parent"
  get "testimonials/student"
  get "testimonials/hostfamily"
  get "testimonials/other"
  get "testimonials/parent1"
  get "testimonials/student1"
  get "testimonials/hostfamily1"
  get "testimonials/other1"
  get "testimonials/detail"
  
  resources :sessions, :only => [:new, :create, :destroy]

  get "users/micropost"
  resources :users do
	member do
		get :following, :followers
	end
  end

  resources :microposts, :only => [:index, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  

  
  
    match '/home', :to => 'pages#home'
	match '/contact', :to => 'pages#contact'
	match '/question', :to => 'pages#question'
	match '/about', :to => 'pages#about'
	match '/help', :to => 'pages#help'
	match '/news', :to => 'pages#news'
	match '/successcase', :to => 'pages#successcase'
	match 'testimonial', :to=> 'testimonials#testimoniallist'
	
	match '/signup', :to => 'users#new'
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	match '/mypost', :to => 'users#micropost'
	
	match '/service', :to => 'pages#service'
	match '/ourteam', :to => 'pages#ourteam'
	match '/whynewhope', :to => 'pages#whynewhope'
	

  root :to => "pages#home"

end

app/models/college_ranking.rb
class CollegeRanking < ActiveRecord::Base
	validates :name_en, :presence => true, :uniqueness=> true 
	validates :name_cn, :presence => true, :uniqueness=> true
	validates :rank, :presence => true
	validates_uniqueness_of :rank, :scope => [:name_en]
	default_scope :order => "school_type, rank"
	
	def force_utf
		if Rails.env.development? 
			attributes.each {|key, value| value.force_encoding('utf-8') if value.encoding != 'utf-8' if value.kind_of?(String) }
		end
	end
end

app/controllers/college_rankings_controller.rb
class CollegeRankingsController < ApplicationController
  before_filter :admin_user 
  before_filter :set_layout 
  # GET /college_rankings
  # GET /college_rankings.xml
  def index
    @college_rankings = CollegeRanking.all.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @college_rankings }
    end
  end

  # GET /college_rankings/1
  # GET /college_rankings/1.xml
  def show
    @college_ranking = CollegeRanking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @college_ranking }
    end
  end

  # GET /college_rankings/new
  # GET /college_rankings/new.xml
  def new
    @college_ranking = CollegeRanking.new
	@college_lists = CollegeList.find_by_sql("select name_en, id from college_lists order by name_en")

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @college_ranking }
    end
  end

  # GET /college_rankings/1/edit
  def edit
    @college_ranking = CollegeRanking.find(params[:id])
	
	@college_lists = CollegeList.find_by_sql("select name_en, id from college_lists order by name_en")
  end

  # POST /college_rankings
  # POST /college_rankings.xml
  def create
    @college_ranking = CollegeRanking.new(params[:college_ranking])

    respond_to do |format|
      if @college_ranking.save
        format.html { redirect_to(@college_ranking, :notice => 'College ranking was successfully created.') }
        format.xml  { render :xml => @college_ranking, :status => :created, :location => @college_ranking }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @college_ranking.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /college_rankings/1
  # PUT /college_rankings/1.xml
  def update
    @college_ranking = CollegeRanking.find(params[:id])

    respond_to do |format|
      if @college_ranking.update_attributes(params[:college_ranking])
        format.html { redirect_to(@college_ranking, :notice => 'College ranking was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @college_ranking.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /college_rankings/1
  # DELETE /college_rankings/1.xml
  def destroy
    @college_ranking = CollegeRanking.find(params[:id])
    @college_ranking.destroy

    respond_to do |format|
      format.html { redirect_to(college_rankings_url) }
      format.xml  { head :ok }
    end
  end
  
  private
	def set_layout
		@curr_menu = "layouts/user_menu"
		@curr_layout = "layouts/user_layout"
	end
end

app/helpers/college_rankings_helper.rb
module CollegeRankingsHelper
end

app/views/college_rankings/_form.html.erb
<%= form_for(@college_ranking) do |f| %>
  <% @college_ranking.force_utf %>
  <% if @college_ranking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college_ranking.errors.count, "error") %> prohibited this college_ranking from being saved:</h2>

      <ul>
      <% @college_ranking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :school_type %><br />
	<%= f.select(:school_type, [["National University", "university"], ["Liberal Arts College", "college"]]) %>
  </div>
  <div class="field">
    <%= f.label :rank %><br />
    <%= f.text_field :rank %>
  </div>
  <div class="field">
    <%= f.label :name_en %><br />
    <%= f.text_field :name_en %>
  </div>
  <div class="field">
    <%= f.label :name_cn %><br />
    <%= f.text_field :name_cn %>
  </div>
  <div class="field">
    <%= f.label :tuition %><br />
    <%= f.text_field :tuition %>
  </div>
  <div class="field">
    <%= f.label :enrollment %><br />
    <%= f.text_field :enrollment %>
  </div>
  <div class="field">
    <%= f.label :acceptance_rate %><br />
    <%= f.text_field :acceptance_rate %>
  </div>
  <div class="field">
    <%= f.label :retention_rate %><br />
    <%= f.text_field :retention_rate %>
  </div>
  <div class="field">
    <%= f.label :graduation_rate %><br />
    <%= f.text_field :graduation_rate %>
  </div>
  <div class="field">
    <%= f.label :class_size %><br />
    <%= f.text_field :class_size %>
  </div>
  <div class="field">
    <%= f.label :sat_act %><br />
    <%= f.text_field :sat_act %>
  </div>
  <div class="field">
    <%= f.label :college_list_id %><br />
	<%= f.select(:college_list_id, "<option value="">--Select a School--</option>" + options_from_collection_for_select(@college_lists, "id", "name_en", "#{@college_ranking.college_list_id}")) %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
	<%= f.select(:status, [["--Select a Status--", ""], ["Active", "active"], ["Inactive", "inactive"]]) %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/college_rankings/edit.html.erb
<h1>Editing college_ranking</h1>

<%= render 'form' %>

<%= link_to 'Show', @college_ranking %> |
<%= link_to 'Back', college_rankings_path %>

app/views/college_rankings/index.html.erb
<h1>Listing college_rankings</h1>

<%= will_paginate @college_rankings %>

<table>
  <tr>
    <th>School type</th>
    <th>Rank</th>
    <th>Name en</th>
    <th>Name cn</th>
	<!--
    <th>Tuition</th>
    <th>Enrollment</th>
    <th>Acceptance rate</th>
    <th>Retention rate</th>
    <th>Graduation rate</th>
    <th>Class size</th>
    <th>Sat act</th>
    <th>College list</th>
    <th>Status</th>
    <th>Year</th>
	-->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @college_rankings.each do |college_ranking| %>
<% college_ranking.force_utf %>
  <tr>
    <td><%= college_ranking.school_type %></td>
    <td><%= college_ranking.rank %></td>
    <td><%= college_ranking.name_en %></td>
    <td><%= college_ranking.name_cn %></td>
	<!--
    <td><%= college_ranking.tuition %></td>
    <td><%= college_ranking.enrollment %></td>
    <td><%= college_ranking.acceptance_rate %></td>
    <td><%= college_ranking.retention_rate %></td>
    <td><%= college_ranking.graduation_rate %></td>
    <td><%= college_ranking.class_size %></td>
    <td><%= college_ranking.sat_act %></td>
    <td><%= college_ranking.college_list_id %></td>
    <td><%= college_ranking.status %></td>
    <td><%= college_ranking.year %></td>
	-->
    <td><%= link_to 'Show', college_ranking %></td>
    <td><%= link_to 'Edit', edit_college_ranking_path(college_ranking) %></td>
    <td><%= link_to 'Destroy', college_ranking, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @college_rankings %>

<br />

<%= link_to 'New College ranking', new_college_ranking_path %>

app/views/college_rankings/new.html.erb
<h1>New college_ranking</h1>

<%= render 'form' %>

<%= link_to 'Back', college_rankings_path %>

app/views/college_rankings/show.html.erb
<% @college_ranking.force_utf %>

<p id="notice"><%= notice %></p>

<p>
  <b>School type:</b>
  <%= @college_ranking.school_type %>
</p>

<p>
  <b>Rank:</b>
  <%= @college_ranking.rank %>
</p>

<p>
  <b>Name en:</b>
  <%= @college_ranking.name_en %>
</p>

<p>
  <b>Name cn:</b>
  <%= @college_ranking.name_cn %>
</p>

<p>
  <b>Tuition:</b>
  <%= @college_ranking.tuition %>
</p>

<p>
  <b>Enrollment:</b>
  <%= @college_ranking.enrollment %>
</p>

<p>
  <b>Acceptance rate:</b>
  <%= @college_ranking.acceptance_rate %>
</p>

<p>
  <b>Retention rate:</b>
  <%= @college_ranking.retention_rate %>
</p>

<p>
  <b>Graduation rate:</b>
  <%= @college_ranking.graduation_rate %>
</p>

<p>
  <b>Class size:</b>
  <%= @college_ranking.class_size %>
</p>

<p>
  <b>Sat act:</b>
  <%= @college_ranking.sat_act %>
</p>

<p>
  <b>College list:</b>
  <%= @college_ranking.college_list_id %>
</p>

<p>
  <b>Status:</b>
  <%= @college_ranking.status %>
</p>

<p>
  <b>Year:</b>
  <%= @college_ranking.year %>
</p>


<%= link_to 'Edit', edit_college_ranking_path(@college_ranking) %> |
<%= link_to 'Back', college_rankings_path %>